[package]
name = "uno-rs"
version = "0.1.0"
authors = ["regalk"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19"
