mod components;
mod router;

use router::{switch, Route};

use yew::prelude::*;
use yew_router::prelude::*;

#[function_component(App)]
pub fn app() -> Html {
    html! {
        <BrowserRouter>
            <Switch<Route> render={switch} />
        </BrowserRouter>
    }
}

fn main() {
    // Comment this line if you don't need logs
    wasm_logger::init(wasm_logger::Config::default());
    // Start hydrate service on the app
    // When the Renderer::hydrate method is called, instead of start 
    // rendering from scratch, Yew will reconcile the Virtual DOM generated by the application with the html string generated by the server renderer.
    yew::Renderer::<App>::new().hydrate();
}
